version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_container_3
    restart: always
    environment:
        MYSQL_DATABASE: 'mysql'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'alibagheri'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'Abcd1234'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'Abcd1234'
        MYSQL_ROOT_user: 'alibagheri'
    ports:
      - "3306:3306"