package main

import (
	m "github.com/labstack/echo/v4/middleware"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
	"log"
	appConfig "remote-task/config"
	"remote-task/domain/giftCart/repository"
	userRepository "remote-task/domain/user/repository"
	"remote-task/infrastructure/persistence/mysql"
	"remote-task/interfaces/http/handler"
	"remote-task/interfaces/http/middleware"
	"remote-task/interfaces/http/routers"
	migrator "remote-task/migrator"
	"time"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	appConfig.Init()
	dbCfg := appConfig.Get().Mysql
	appCfg := appConfig.Get().App
	applyMigrations := appCfg.ApplyMigrations
	repo, err := mysql.NewRepositories(dbCfg.Username, dbCfg.Password, dbCfg.Port, dbCfg.Host, dbCfg.Name)
	if err != nil {
		panic(err)
	}
	defer repo.Close()
	if applyMigrations {
		if err := migrator.New(repo).Run("up", 0); err != nil {
			log.Printf("serve migration error: %v\n", err)
		}
	}
	GiftCarRepo := repository.NewGiftCardRepository(repo)
	UserRepo := userRepository.NewUserRepository(repo)
	giftCartService := handler.NewGiftCartHandler(GiftCarRepo, UserRepo)
	generalService := handler.NewGeneralHandler()
	handlers := handler.New(*giftCartService, *generalService)
	router := routers.NewRouter()
	router.Use(middleware.HealthCheck(repo))
	router.Use(m.CORS())
	router.Use(middleware.CORS())

	routers.RegisterRoutes(router, handlers)
	routers.NewServer(router, appCfg.Port, time.Duration(1)).StartListening()
}
